### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aerjayc** [aerjayc/pyarchiver#1]
## Wayback Machine
- [ ] Add support for searches
- [ ] When returning archived urls, include metadata (parse from results)

## archive.today
- [ ] Add support for submitting urls (i.e. support javascript)
- [ ] Add support for searches
- [ ] When returning archived urls, include metadata (parse from results)
